### ISSUE TITLE
Améliorer le readme

### ISSUE THREAD

**Issue by joedioufy** [Code-for-Senegal/vie-publique.sn#15]
### Contexte

J'ai rencontrer un soucis sur l'installation du projet, j'ai eu ce soucis : 
<img width="957" alt="image" src="https://github.com/user-attachments/assets/7187e7d3-5e31-4646-80eb-18f06413e9ed">

L'erreur indique que le module @nuxtjs/web-vitals nécessite un identifiant googleAnalytics.id pour intégrer Google Analytics dans le projet. Sauf que le GTAG_ID se trouve dans le fichier .env.example.

### ATTENDU
Préciser dans le readme qu'il faut bien copier le fichier .env.example avant de run le projet (pour les futures installations du projet)

**Comment by malicktech** [comment]
@joedioufy en effet c'est une précision qui manquait, j'ai mis ces instructions bien après la section run dev. 
J'ai corrigé.

merci pour ta contribution

**Comment by malicktech** [comment]
Done

**Comment by joedioufy** [comment]
@malicktech : Top, j'avais déjà ajouter cette partie sur une branche, je n'avais pas les droits pour push ma branche.
Peux tu m'ajouter pour que j'envoie une amélioration de la barre de navigation stp
