### ISSUE TITLE
Législative 2024 - Carte électorale interactive

### ISSUE THREAD

**Issue by malicktech** [Code-for-Senegal/vie-publique.sn#33]
# Intégration d'une carte électorale interactive du Sénégal (Législatives 2024)

## Description du besoin

Nous souhaitons intégrer une carte électorale interactive représentant les départements du Sénégal et de la diaspora dans une section dédiées du site aux élections 2024 du 17 Novembre

### Objectifs

- Afficher une carte choroplèthe interactive des départements du Sénégal et de la diaspora
- Visualiser les données électorales par département/région (électeurs, bureaux, lieux de vote)
- Assurer une performance optimale du rendu et de l'interactivité
- Privilégier des solutions open source

### Données disponibles

**Format Données nationales:**
```
Region, Departement, Commune, LieuDeVote, Bureau, Electeurs, Implantation
```

**Format Données diaspora:**
```
RepDiplomatique, Pays, Localite, LieuDeVote, Numero, Bureau, Electeurs
```

Voir les données extraite ici
https://github.com/Thialala/sunu-election-pr-2024/tree/main

Les données n'ont pas évolué depuis les légistatives

### 1. Solution SVG + GeoJSON (Recommandée)

**Avantages:**
- Performance optimale (fichier statique)
- Pas de dépendance à un service tiers de tuiles
- Personnalisation totale du style
- Taille de bundle réduite

**Mise en œuvre:**
1. Convertir les données géographiques du Sénégal en GeoJSON optimisé
2. Générer un SVG
3. Implémenter l'interactivité avec Vue.js/Nuxt
4. connecter aux données de l'API

### 2. Solution OpenStreetMap + Leaflet

**Avantages:**
- Familiarité des utilisateurs avec l'interface de carte
- Contexte géographique plus riche
- Zoom et navigation intuitifs
- intégration des données côté CMS

**Inconvénients:**
- Dépendance aux tuiles OSM
- Performance potentiellement impactée par le chargement des tuiles
- Bundle size plus important

**Librairies potentielles:**
- `[Nuxt Leaflet](https://leaflet.nuxtjs.org/)` pour l'intégration avec Nuxt/Vue.js
- `leaflet-choropleth` pour la visualisation des données

### 3. Solution hybride avec MapLibre GL JS

**Avantages:**
- Support du rendu vectoriel
- Performance optimisée
- Possibilité de caching des tuiles

**Inconvénients:**
- Complexité d'implémentation plus importante
- Nécessite plus de configuration

## Questions ouvertes

- Quelle granularité de zoom et quel découpage (région/département) sur la carte?
- Comment gérer l'affichage de la diaspora (carte séparée)?

## Ressources utiles

- [données carte 2024 DGE](https://github.com/Thialala/sunu-election-pr-2024/tree/main)
- [données geojson ](https://www.africageoportal.com/datasets/c741b6c0cb404a42a702ff4999c0bc90/about)
- [Documentation D3-geo](https://github.com/d3/d3-geo)
- [Tutoriel cartes choroplèthes avec D3](https://observablehq.com/@d3/choropleth)
- [Données géographiques du Sénégal (GADM)](https://gadm.org/download_country.html)

**Comment by malicktech** [comment]
@tonux a importé les listes des départements sous format Geojson dans le CMS

Données de bases : https://senegal.africageoportal.com/maps/6ec9d1cf60944eaba2ec776147270ddb/about

J'ai testé une intégration au front avec la solution 2: Nuxt Leaflet + Open streep map

![image](https://github.com/user-attachments/assets/b5f9ab1a-d3a4-441f-a9e6-9b5695d1006f)

![image](https://github.com/user-attachments/assets/4ed6786e-71f1-461e-bdcb-eefa30ebc7ef)

**Comment by malicktech** [comment]
@NdeneSENE étudie solution 1: SVG + GeoJSON

objectif, afficher une carte de ce style qui sera réutilisée pour les résultats des élections

![image](https://github.com/user-attachments/assets/15fd36bb-d9b5-4b11-a6e2-887073662992)

**Comment by malicktech** [comment]
Structuration proposée par @tonux

Carte:  [departement, region, position]

departement -> one to may -> bureau_vote: Un département peut contenir plusieurs bureaux de vote

bureau_vote -> resultat : Chaque bureau de vote peut avoir des résultats pour chaque liste de candidats.

liste_candidat -> candidat

**Comment by malicktech** [comment]
intégration DONE avec la solution 2: Nuxt Leaflet + Open streep map

![image](https://github.com/user-attachments/assets/d23122db-7871-4b54-95c6-caa08968981d)

**Comment by tonux** [comment]
Bravo team. Good job
