### ISSUE TITLE
Législative 2024

### ISSUE THREAD

**Issue by malicktech** [Code-for-Senegal/vie-publique.sn#34]
## Objectif: 
- Ajouter un espace dédié aux élections législatives 2024
- proposer les données de la DGE, enrichies, et mieux présentés

## Features
- consultation des coalitions et candidats, avec photos
- consultation de statistiques (profession, présence des listes, répartitions des électeurs etc.)
- consultation de la carte électorale sous forme de map/tableau avec recherche  #33 
- consultation des résultats le jour J sous forme de map/tableau avec recherche

J'ai push effectué sur la branche suivante
https://github.com/Code-for-Senegal/vie-publique.sn/tree/feat/election-2024

## URL 

v1 déployé les listes et stats à consulter ici https://www.vie-publique.sn/elections

## Screen

![image](https://github.com/user-attachments/assets/ce325fba-2455-4183-a8bc-59012a6027a0)
![image](https://github.com/user-attachments/assets/16ff9965-6fb5-4e56-b299-f92fcfd05a14)
![image](https://github.com/user-attachments/assets/6a743290-0bad-4cb9-9b51-13ea5151249c)
![image](https://github.com/user-attachments/assets/9027658a-b9cb-45b0-9583-f4bc8ad5a3fe)
![image](https://github.com/user-attachments/assets/6932464d-c64c-4cec-8075-c042418732cf)
![image](https://github.com/user-attachments/assets/0ecda01b-d87b-4892-9c55-85125b7be7a8)
![image](https://github.com/user-attachments/assets/12d91568-a2e9-4474-8603-969c66987555)

**Comment by malicktech** [comment]
@njaga propose une refonte de la page d'accueil pour mieux mettre en avant le bloc election législatives

**Comment by cisse410** [comment]
Pour la partie statistiques.

Par exemple, si on clique sur une profession, on affiche une sorte de diagramme or something like that pour la répartition de cette profession sur les différentes coalitions

**Comment by malicktech** [comment]
Sujet restant à traiter: l'intégration des résultats du vote et des PV.

Objectifs : 
- centraliser les PV dans une page au fur et à mesure qu'elle seront dispo le jour J
- projet le résultat des départements sur une carte
