### ISSUE TITLE
Mise en place de la B.D parlementaire

### ISSUE THREAD

**Issue by joedioufy** [Code-for-Senegal/vie-publique.sn#38]
### CONTEXTE
Créer la structure de la base de données pour stocker les informations des députés, les plénières, les projets de loi, et les votes.

### TÂCHES
- [ ] Créer les tables suivantes :

- [ ] Deputes :

- Compléter la table des députés: ajouter sa circonscription, son status (titulaire ou suppléant) et ses mandats précédents.

- [ ] Ajouter table PLENIERE

-  id, date, ordre_du_jour.

- [ ] Ajouter table PROJETS_LOI

-  id, titre, resume, statut_legislatif, thematiques, pleniere_id.

- [ ] Ajouter table VOTE

-  id, depute_id, projet_loi_id, vote (Pour, Contre, Abstention).

### Critères d’acceptance
La structure de la base de données est opérationnelle et peut être interfacée avec l’application.
Les tables sont bien reliées avec les clés étrangères appropriées (depute_id, pleniere_id).

**Comment by cisse410** [comment]
Pour la table PROJETS_LOI, on pourrait peut-être ajouter l'id du député qui a  proposé ce projet de loi, si c'est une proposition emmenant d'un député bien sûr (vu que parfois les députés pourront soumettre des projets de lois) pour pourvoir afficher le député en question []()https://github.com/Code-for-Senegal/vie-publique.sn/issues/42#issue-2698685478

**Comment by joedioufy** [comment]
@cisse410 : Effectivement, bien vu. Je vais l'ajouter

**Comment by malicktech** [comment]
hello, un bon début, ont peut élargir la réflexion pour rendre la bdd plus flexible et complète. 
Il faut surtout coller au règlement intérieur et au code électoral.

il y'a quelques éléments supplémentaires à intégrer par exemple
- le bureau de l'assemblée (le président, 8 vice président, le secrétaire et questeurs)
- les 14 commissions permanentes, leurs membres et composition de bureaux
- les travaux des commissions
- Commission d’enquête parlementaire 
- 𝐪𝐮𝐞𝐬𝐭𝐢𝐨𝐧 𝐞́𝐜𝐫𝐢𝐭𝐞 des députés
- Mission d’information parlementaire des commissions
- Audition plénière ou en commission
- les remplacements de députés, démissions et demandes de suspensions de députés 
- les radiations de députés de députés
- le calendrier parlementaire 
- le fonctionnement de l'assemblée
- les projets ou proposition de loi, an

Un peut programmer un atelier avec @tonux pour affiner tout çà et commencer à réfléchir à la partie backend DIRECTUS

et voir comment récupérer les données des élections, la table candidats notamment.

**Comment by malicktech** [comment]
Suite point du samedi 07/12
et Atelier avec Tonux ce 08/12 
nous avons commencé a structurer la bdd dans le CMS directus
![Image](https://github.com/user-attachments/assets/5119d4f6-d87e-4619-8fd3-18b1a58ea9de)

**Comment by cisse410** [comment]
Est-ce que vous avez pris en compte du fait qu'un député peut adresser des questions écrites/orales au gouvernement ? Ceci pourrait permettre d'avoir une vue globale sur ces questions @malicktech @joedioufy @tonux

**Comment by malicktech** [comment]
@cisse410 une bonne remarque, j'intègre cela dans les specs, j'ai vu des députés publier déjà des questions
