### ISSUE TITLE
Proposition d'amélioration de la navigation depuis l'accueil

### ISSUE THREAD

**Issue by dofbi** [Code-for-Senegal/vie-publique.sn#4]
Hello @malicktech,

Merci pour l'amélioration de la page d'accueil, j'aime beaucoup. Voici quelques suggestions :

![Capture d’écran du 2024-07-13 22-02-06](https://github.com/user-attachments/assets/c822eb12-762d-4891-8152-a0c8bda8f84a)

- **Barre de recherche**
- **Navigation**
  - Depuis l'accueil, pouvoir cliquer sur les sous-catégories, par exemple :
    - Jeux : sous-catégories (organisation de l'état, photo nomination)
    - Rapport : sous-catégories (cours des comptes, OFNAC, IGE, ARMP)
  - Ajouter une page contact
  - Revoir le nom de la rubrique "Rapport" pour inclure d'autres types de documents

**Comment by malicktech** [comment]
Petit amélioration sur la page d'accueil
- navbar hozirontal en full page
- Ajout d'icone sur la navbar hozirontal
- Ajout de cercle vert autour des icones pour un meilleur rendu

![image](https://github.com/user-attachments/assets/18965a92-10fd-4eda-9a09-985eb028deab)

**Comment by malicktech** [comment]
hello @dofbi 

je souhaiterai avoir ton avis sur la réorganisation de la navigation suite à l'ajout de nouvelle page.

Pour l'instant nous avons :
- Journal officiel
- Nominations (Annuaire de l'exécutif)
- Justice (Annuaire, textes ...) 
- Rapports d'audit (ofnac, cdc, ige ..)
- code général (constitution etc.)
- Conseil des ministres (communiqués)
- Quiz Jeux
- Actualités (conseil interministériel, communiqué, articles ...)
  - [lien env test ](https://senegal-rapports.netlify.app/publications/actualites)
- Baromètre promesses électorale (en cours)
  - [lien env test baromètre](https://senegal-rapports.netlify.app/barometre-politique) 
- Guide (des articles de vulgarisation sur les institutions et le fonctionnement de l'état)

Comment penses tu que devrait s'organiser tout cela entre le menu la navbar, la sidebar sur mobile et la page d'acceuil.

Comment dynamiser et rendre plus attrayant la page d'acceuil ?

@NdeneSENE @joedioufy @mbayedione10  vos avis sont aussi les bienvenus si votre temps vous le permet

Merci d'avance à tous pour vos contributions

**Comment by dofbi** [comment]
Hello @malicktech , bonjour à tous, Nice work 🎉 

Merci pour vos réactivités et vos nouvelles propositions. Voici quelques points essentiels pour toujours améliorer la navigation et la page d'accueil du site vie-publique.sn

## 1. Importance des Types de Contenus

Pour refléter notre mission de vulgariser et de rendre l'information publique plus accessible, il est crucial de distinguer les types de contenus :

- **Contenus Exclusifs** 📊 : Ce sont des informations que nous avons produites, traitées, et analysées. Ils représentent notre véritable valeur ajoutée et doivent être mis en avant sur le site.

- **Contenus Publiés** 📰 : Ce sont des informations provenant de sources externes, publiées sans modifications majeures. Ils seront présentés de manière secondaire.

![Capture d’écran du 2024-08-19 18-23-47](https://github.com/user-attachments/assets/d09afba1-83de-4c85-8cac-d4d726622bfe)

## 2. Réorganisation des Groupes de Contenus

![Capture d’écran du 2024-08-19 18-23-34](https://github.com/user-attachments/assets/5d947692-7e49-4c30-b9f4-b2c539f93def)

Pour simplifier la navigation et organiser les informations, nous proposons les rubriques suivantes :

- **Documents**  
  Inclut les rapports d'audit, journaux officiels, codes, et autres documents officiels.

- **Découverte**  
  Contient les guides sur les institutions et le fonctionnement de l'État, ainsi que les quiz pour tester les connaissances.

- **Services**  
  Regroupe les outils comme les annuaires et les clés d'accès à des informations spécifiques.

- **Actualités**  
  Regroupe les actualités et communiqués récents.

- **Contributions**  
  Participation citoyenne, apportez votre regard et expérience


## 3. Mise en Avant des Contenus

Sur la page d'accueil, nous mettrons en avant :

- Les derniers rapports et documents importants 📑
- Les dernières nominations 🏅
- Les actualités récentes 🗞️

![Capture d’écran du 2024-08-19 18-23-16](https://github.com/user-attachments/assets/8b90d76a-b6d1-4997-9cd9-fc12778ceba7)

Cela permettra de rendre les contenus essentiels plus visibles et accessibles pour tous les utilisateurs.

Merci pour vos contributions et vos avis sur ces propositions.

Bien à vous,

**Comment by joedioufy** [comment]
Faisant suite à ta proposition @dofbi : 

<img width="615" alt="image" src="https://github.com/user-attachments/assets/091c3131-51e4-4837-aa03-3456371e1579">

Je peux partir sur ce menu si c'est good pour vous.

**Documents (dropdown) :** 
- Rapports d'audit, 
- Journaux officiels, 
- Codes, 
- Autres documents officiels

**Découverte**
- Guides
- Fonctionnement de l'État
- Quizz

**Services**
- Annuaires
- Outils pratiques

**Actualité**

**Comment by malicktech** [comment]
en phase avec les 5 rubriques proposés par @dofbi 
avec une petite réserve sur le nom de la rubrique service, je propose de réfléchir autre nom qui fera moins référence à la vente de service, je pensais à Outils, ou Annuaire si la rubrique ne contient que des annuaires (gouvernement, député, etc ..)

@joedioufy 
Merci pour la proposition j'aime bien perso.

**Sur Desktop :** 
on peut garder sur deux niveaux la navbar comme proposé, avec des dropdown sur certaines rubriques.

**Sur Mobile**
quel serait l'affichage ? 

**Champs de recherche**
mais pour le champs de recherche, j'aimerai bien qu'a terme ca soit le point d'entrée
avec un moteur de recherche intelligent capable de rechercher la bonne info sur tout le site
un peu dans le style de la première proposition de Mamadou
![image](https://github.com/user-attachments/assets/aca0e352-97ee-40d4-9f8b-d4d51d22396f)

**Comment by malicktech** [comment]
Réorganisation de la page d'accueil démarrée

![image](https://github.com/user-attachments/assets/6e3f0583-b18f-4c59-a81b-ee8a9555a5c4)

J'ai créé une première page sous catégorie **documents**

![image](https://github.com/user-attachments/assets/6a15cd7c-a4f1-45fd-8cda-234514597a5d)

**Comment by joedioufy** [comment]
Vue desktop
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/3026e020-b2aa-4fa1-a376-423ad6e2aef2">

Vue mobile
<img width="436" alt="image" src="https://github.com/user-attachments/assets/ec6f2d24-e098-4979-b577-cce4852cfafe">

**Comment by mbayedione10** [comment]
Bonjour à tous,

Félicitations pour le travail effectué jusqu'ici !

@malicktech , après l'ajout des actualités sur la page d'accueil, voici l'affichage que nous avons actuellement sur la vue tablette : 
![image](https://github.com/user-attachments/assets/28205f0a-5d97-456a-88b5-295b1d044917)

**Suggestion d'amélioration :**
Pour une meilleure lisibilité et utilisation de l'espace, je propose que nous organisions les actualités en un bloc de 4 cartes.

**Comment by malicktech** [comment]
@mbayedione10 Bonjour, merci pour la suggestion, c'est mieux ainsi en effet. 

Vue desktop

![image](https://github.com/user-attachments/assets/98fef319-872b-49b5-84ae-d5be5cb3e874)

Vue mobile, je trouve que c'est trop long à scroller de garder les élements d'un card en col, j'ai adapté en row et ca donne çà : 

![image](https://github.com/user-attachments/assets/631df181-5c5d-4243-8c22-812a5bc838b5)

**Comment by malicktech** [comment]
@dofbi @joedioufy @NdeneSENE une proposition que viens de m'envoyer un designer bénévole sur twitter 

![image](https://github.com/user-attachments/assets/6b1f31e1-c29e-4115-96e4-76de14e1a2a2)
