### ISSUE TITLE
Bureau de l'assemblée nationale

### ISSUE THREAD

**Issue by malicktech** [Code-for-Senegal/vie-publique.sn#45]
Intégrer la composition du bureau de l'assemblée nationale
1 président
8 vice présidents
6 secrétaires élus
2 Questeurs

**Comment by Ceerno** [comment]
@malicktech  les commissions ne font pas partie du bureau ? ce serait pertinent de gérer les membres

**Comment by malicktech** [comment]
non, les commissions sont différentes, ils sont régit par l'article 24, chapitre 29 du RI
CF : https://www.vie-publique.sn/pdf/codes/assemblee-nationale-loi-2002-20-du-15-mai-2002-reglement-interieur.pdf

je vais mettre à jour les specs et organiser un atelier sur le sujet ca sera plus simple
